# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multi_question_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from nodeeditor.utils import dumpException


class Ui_multy_question_gui(object):
    def __init__(self, q):
        super().__init__()
        self.next = None
        self.callback = None
        self.q = q

    def setupUi(self, multi_question_gui):
        multi_question_gui.setObjectName("open_question_gui")
        multi_question_gui.resize(700, 800)
        self.window = multi_question_gui
        self.widget = QtWidgets.QWidget(multi_question_gui)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 700, 800))
        self.widget.setObjectName("widget")
        self.quetion_txt = QtWidgets.QLabel(self.widget)
        self.quetion_txt.setGeometry(QtCore.QRect(60, 30, 181, 51))
        self.quetion_txt.setObjectName("quetion_txt")
        self.next_btn = QtWidgets.QPushButton(self.widget)
        self.next_btn.setGeometry(QtCore.QRect(60, 650, 100, 50))
        self.next_btn.setObjectName("next_btn")
        self.next_btn.clicked.connect(self.next_on_click)
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(60, 100, 600, 500))
        self.groupBox.setObjectName("groupBox")
        self.checkBox1 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox1.setGeometry(QtCore.QRect(10, 50, 300, 30))
        self.checkBox1.setObjectName("checkBox1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 90, 300, 30))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 130, 300, 30))
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 170, 300, 30))
        self.checkBox_4.setObjectName("checkBox_4")
        self.checkBox_6 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_6.setGeometry(QtCore.QRect(10, 210, 300, 30))
        self.checkBox_6.setObjectName("checkBox_6")
        self.checkBox_5 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_5.setGeometry(QtCore.QRect(10, 250, 300, 30))
        self.checkBox_5.setObjectName("checkBox_5")

        self.retranslateUi(multi_question_gui)
        QtCore.QMetaObject.connectSlotsByName(multi_question_gui)

    @property
    def get_ans(self):
        ans = []
        if self.checkBox1.isChecked():
            ans.append(self.checkBox1.text())
        if self.checkBox1.isChecked():
            ans.append(self.checkBox_2.text())
        if self.checkBox_3.isChecked():
            ans.append(self.checkBox_3.text())
        if self.checkBox_4.isChecked():
            ans.append(self.checkBox_4.text())
        if self.checkBox_5.isChecked():
            ans.append(self.checkBox_5.text())
        if self.checkBox_6.isChecked():
            ans.append(self.checkBox_6.text())
        return ans

    def next_on_click(self):
        self.callback({"question": self.q, "answer": self.get_ans})
        if self.next is None:
            print("here")
            self.window.close()
        else:
            try:
                self.window.close()
                self.new_window = QtWidgets.QDialog()
                self.next.setupUi(self.new_window)
                self.new_window.exec_()
            except Exception as e:
                dumpException(e)

    def retranslateUi(self, open_question_gui):
        _translate = QtCore.QCoreApplication.translate
        open_question_gui.setWindowTitle(_translate("open_question_gui", "Dialog"))
        self.quetion_txt.setText(_translate("open_question_gui", self.q['text']))
        if self.next is None:
            self.next_btn.setText(_translate("open_question_gui", "Finish"))
        else:
            print("here")
            self.next_btn.setText(_translate("open_question_gui", "Next"))
        self.groupBox.setTitle(_translate("open_question_gui", "Choose One Answer"))
        self.checkBox1.setText(_translate("open_question_gui", self.q['options'][0]))
        self.checkBox_2.setText(_translate("open_question_gui", self.q['options'][1]))
        if(len(self.q['options'])>2):
            self.checkBox_3.setText(_translate("open_question_gui", self.q['options'][2]))
        else:
            self.checkBox_3.setVisible(False)
        if (len(self.q['options']) > 3):
            self.checkBox_4.setText(_translate("open_question_gui", self.q['options'][3]))
        else:
            self.checkBox_4.setVisible(False)
        if (len(self.q['options']) > 5):
            self.checkBox_6.setText(_translate("open_question_gui", self.q['options'][5]))
        else:
            self.checkBox_6.setVisible(False)
        if (len(self.q['options']) > 4):
            self.checkBox_5.setText(_translate("open_question_gui", self.q['options'][4]))
        else:
            self.checkBox_5.setVisible(False)


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    open_question_gui = QtWidgets.QDialog()
    ui = Ui_multy_question_gui()
    ui.setupUi(open_question_gui)
    open_question_gui.show()
    sys.exit(app.exec_())
