# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tests_enter_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from nodeeditor.utils import dumpException


class Ui_Test_Dialog(object):
    def __init__(self, q):
        super().__init__()
        self.next = None
        self.callback = None
        self.q = q
    def setupUi(self, Test_Dialog):
        Test_Dialog.setObjectName("Test_Dialog")
        Test_Dialog.resize(600, 600)
        self.widget = QtWidgets.QWidget(Test_Dialog)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 600, 600))
        self.widget.setObjectName("widget")
        self.test_name = QtWidgets.QLabel(self.widget)
        self.test_name.setGeometry(QtCore.QRect(40, 30, 400, 70))
        self.test_name.setObjectName("test_name")
        font = QtGui.QFont()
        font.setPointSize(15)
        self.test_name.setFont(font)
        self.result_line = QtWidgets.QLineEdit(self.widget)
        self.result_line.setGeometry(QtCore.QRect(40, 140, 400, 70))
        self.result_line.setObjectName("result_line")
        self.next_btn = QtWidgets.QPushButton(self.widget)
        self.next_btn.setGeometry(QtCore.QRect(40, 250, 400, 70))
        self.next_btn.setObjectName("next_btn")

        self.retranslateUi(Test_Dialog)
        QtCore.QMetaObject.connectSlotsByName(Test_Dialog)

    def retranslateUi(self, Test_Dialog):
        _translate = QtCore.QCoreApplication.translate
        Test_Dialog.setWindowTitle(_translate("Test_Dialog", "Dialog"))
        self.test_name.setText(_translate("Test_Dialog", q['']))
        self.result_line.setPlaceholderText(_translate("Test_Dialog", "Result"))
        self.next_btn.setText(_translate("Test_Dialog", "Next"))

    def next_on_click(self):
        self.callback({"name": self.q, "result": self.result_line.test()})
        if self.next is None:
            self.window.close()
        else:
            try:
                self.window.close()
                self.new_window = QtWidgets.QDialog()
                self.next.setupUi(self.new_window)
                self.new_window.exec_()
            except Exception as e:
                dumpException(e)

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    open_question_gui = QtWidgets.QDialog()
    ui = Ui_Test_Dialog({"test": "hello"})
    ui.setupUi(open_question_gui)
    open_question_gui.show()
    ans = []
    ui.next = Ui_Test_Dialog({"test": "hii"})
    def callback(answers):
        ans.append(answers)
    ui.callback = callback
    ui.next.callback = callback
    sys.exit(app.exec_())
